version: "3"
services:
  burnbroker:
    image: ${DOCKER_IMAGE:-quocpm/burnbroker:latest}
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WC_PROJECT_ID=${NEXT_PUBLIC_WC_PROJECT_ID:-}
    restart: always
